### ISSUE TITLE
Still the Best.  Thanks.  (Not really an issue.)

### ISSUE THREAD

**Issue by hexagon5un** [triffid/gcodeview#19]
I went looking for a standalone gcode viewer just recently, having used gcodeview since you wrote it, but not for a few years.

Nobody's made anything that's not web-based or useless from the keyboard.  gcodeview still gets the job done, fast and easy.  Thanks.

**Comment by triffid** [comment]
Glad you enjoy it, and that I apparently nailed my design goals :)

Feel free to send pull requests if you modernize anything, I haven't really looked at it in a while!
