### ISSUE TITLE
won't build on ubuntu

### ISSUE THREAD

**Issue by triffid** [triffid/gcodeview#6]

**Comment by Traumflug** [comment]
Without hijacking this Issue, compilation out of the box doesn't work on Ubuntu either. What I did:

```
sudo apt-get install libsdl1.2-dev
sudo apt-get install ftgl-dev
make
```

Result:

```
cc -O2 -std=c99  -Wall `pkg-config --cflags sdl ftgl fontconfig gl` -std=c99 -c main.c -o main.o
<a few warnings>
cc `pkg-config --libs sdl ftgl fontconfig gl` -lm main.o -o gcodeview
main.o: In function `timerCallback':
main.c:(.text+0x22): undefined reference to `SDL_PushEvent'
main.o: In function `gline':
main.c:(.text+0x2c4): undefined reference to `glColor4f'
main.c:(.text+0x30f): undefined reference to `hypotf'
-- and about 100 such lines more --
```

**Comment by Traumflug** [comment]
Another tidbit:

```
>$ pkg-config --libs sdl ftgl fontconfig gl
-lSDL -lftgl -lfontconfig -lGL
```

**Comment by triffid** [comment]
@traumflug, sounds like something is broken there- **hypotf** is a basic system function from libmath (libm.so) that comes with glibc and listed in **math.h**!

I assume you have build-essential and sdl-dev or whatever it is you need on ubuntu...

Those other undefined references are fairly basic functions that should be found in SDL.h and SDL_opengl.h and friends.. are any of the warnings it not finding necessary headers?

What warnings does it display? what does `pkg-config --cflags sdl ftgl fontconfig gl` print?

looks like this here:
`$ pkg-config --cflags sdl ftgl fontconfig gl
-D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/SDL -I/usr/include/FTGL -I/usr/include/freetype2 -I/usr/include/libdrm`

If you do find what you need to do to fix it, please let us know :)

**Comment by triffid** [comment]
for libs, mine says

`$ pkg-config --libs sdl ftgl fontconfig gl
-lSDL -lpthread -lftgl -lfontconfig -lGL` which considering I don't use threads seems about right.

so now the puzzle is, why can your system not find the symbols listed in the headers in their respective libraries?

see what this does:
`$ echo 'int main() { printf("%f\n", hypotf(1.0, 1.0)); }' > test.c && gcc test.c && ./a.out
test.c: In function 'main':
test.c:1: warning: incompatible implicit declaration of built-in function 'printf'
test.c:1: warning: incompatible implicit declaration of built-in function 'hypotf'
1.414214`

or for a more technically correct and complete test,

`$ echo $'#include <math.h>\n#include <stdio.h>\nint main() { printf("%f\\n", hypotf(1.0, 1.0)); }' > test.c && gcc -lm test.c && ./a.out
1.414214`

I'd understand if the first one doesn't work, it really is missing a few key pieces but the 2nd one should absolutely work just fine

**Comment by Traumflug** [comment]
Hah! Got it. It's simple, libraries have to appear after the object. Accordingly:

```
$ git diff
diff --git a/Makefile b/Makefile
index a893d60..09f5632 100644
--- a/Makefile
+++ b/Makefile
@@ -15,7 +15,7 @@ OBJECTS               = $(SOURCES:.c=.o)
 all: $(SOURCES) $(EXECUTABLE)

 $(EXECUTABLE): $(OBJECTS)
-       $(CC) $(LDFLAGS) $(OBJECTS) -o $@
+       $(CC) $(OBJECTS) $(LDFLAGS) -o $@

 %.o: %.c
        $(CC) $(CFLAGS) -std=c99 -c $< -o $@
```

I thought they'd have sorted this centuries old problem out by 2012. It's gcc 4.6.1.

Can you fix it without requiring me to do a fork?

**Comment by triffid** [comment]
yep that's easy, thanks for investigating :)

**Comment by triffid** [comment]
0d6fa1a
